# permissions for end users to edit ingressscriptinjectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ingress-injection
    app.kubernetes.io/managed-by: kustomize
  name: ingressscriptinjector-editor-role
rules:
- apiGroups:
  - ingress.digitalist.cloud
  resources:
  - ingressscriptinjectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingress.digitalist.cloud
  resources:
  - ingressscriptinjectors/status
  verbs:
  - get
