apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-script-injector-rolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ingress-injection-system
roleRef:
  kind: ClusterRole
  name: manager-role
  apiGroup: rbac.authorization.k8s.io